### ISSUE TITLE
Cider 2.0 Tracker Issue

### ISSUE THREAD

**Issue by EclecticGriffin** [calyxir/calyx#1913]
We're finally at point where we can start running programs through Cider 2 and thus it now makes sense to have a tracker for the ongoing efforts to reach parity with Cider 1.

Known issues:
- [x] #1968
- [x] #2044
- [x] Missing a bunch of primitives
  - [x] Comb primitives are partially done (#1967)
  - [x] Seq Mems (#1967)
  - [x] Mult / Smult (#2128) 
  - [x] Div / Sdiv (#2158) 
  - [x] Sqrt (#2158)
  - [x] Bit slice (#2218)
  - [x] Fixed Point (#2235)
- [x] #2159
- [x] Group termination takes an extra cycle due to only running convergence once. Issue: #1917 
- [x] Continuous assignments (#2064)
- [x] `par` not supported (#2043)
  - [x] ~~cross branch conflicts warnings missing~~ Skipping in favor of more direct thinking about `par` stuff
- [x] `with` not supported (#2064)
- [x] `invoke` not supported (#2119) 
- [x] `repeat` not supported (#2158)
- [x] multi-component programs not supported (#2119)
- [x] #2161
- [x] #2219
- [x] (Debugger) Add watchpoint enable/disable  (#2250)

**Comment by rachitnigam** [comment]
For some of these issues, like `with` not being supported, we should resolve the long-running `with` discussion and decide if we want to get rid of it completely or not.

**Comment by EclecticGriffin** [comment]
@rachitnigam Agreed, this is mostly just me getting down the current state of things. Also `with` is annoying to implement so I've thus far avoided it oops

**Comment by sampsyo** [comment]
Wahoo; thank you for summarizing! Just capturing the synchronous discussion a little bit, on this point:

> Does not generate an output JSON compatible with our testing infrastructure

I had suggested, in the spirit of trying to do the simplest possible thing here, that it might not be too hard to load/dump "raw bits," i.e., the exact bit-level contents of the memories. This is more or less what the RTL simulators already do (they are using hex-encoded text, but same difference). We could then pre-/post-process these files into our JSON format externally, alleviating the need for any `serde` hacking on Cider's side.

This of course omits all the non-memory results that Cider 1.0 can already produce. But I believe this is fine: all we really need to check correctness is those memory dumps.

**Comment by EclecticGriffin** [comment]
Officially closing this tracker since at this point Cider 2 has replaced Cider 1 and has passed parity in terms of programs
