### ISSUE TITLE
[Profiling] Tracker Issue for Profiling first steps

### ISSUE THREAD

**Issue by ayakayorihiro** [calyxir/calyx#2014]
This issue lists out steps for profiling! (Mostly so I can organize my TODOs.) Will update as I move along.

### Inspections & QoL improvements to profiler

- Running the profiler on more (big) programs
  - [x] Make a test suite for profiling
  - [ ] Use Cider2 benchmarks for "real programs"
    - [ ] Brainstorm ways to give actionable feedback for bigger programs
  - [ ] Fix profiler tests CI
    - Have runt test print out more things to properly debug
- Inspections
  - [x] Look through the waveforms for the "weird behavior"/mystery cycles
  - [x] Minimization to see different behaviors
  - [x] For any FSM-managed group, collect two pieces of info and report both to the users. The diff would display the mystery redundant cycles that Calyx is consuming.
    - ground truth (`go`, `done` ports)
    - FSM (what Calyx says is _allowed_ to run) 
- QoL improvements:
  - [ ] Connect invokes & pars (cond groups for whiles?) with user identifiable info (line numbers?)
- Visualizations
  - [x] Check out README: https://github.com/Auterion/embedded-debug-tools/tree/main/ext/orbetto
  - [x] Check out: https://ui.perfetto.dev/
  - [x] Check out: https://profiler.firefox.com/
  - [x] Make a first-pass visualization for cycle counts
  - [x] Find tools that display flame graphs (rather than a timeline view)

### First Pass: Cycle-level performance info at the Calyx level

- Metadata generation
   - [x] Print JSON from TDCC (add another pass option to print JSON instead of the dump)
   - [x] Write JSON to file
   - [x] Instead of hacking through the enable assignment, we directly keep track of group to FSM state mappings
      - [x] Refactor this by directly building a `FSMStateInfo` when processing enables.
   - [x] Fix JSON emission to output a single JSON file at the end (when there are multiple TDCC groups, like in `language-tutorial-iterate`, the individual TDCC FSMs overwrite each other)
   - [x] ~Right now (for optimization purposes?) the first group is morphed with the setup. Want to differentiate for more accurate counts of the first group.~
   - [ ] Merge `dump-fsm` and `dump-fsm-json` for TDCC
   - [x] Add FSM name information to JSON
   - [x] If the par arm/component does not yield a FSM, need to output corresponding information (check `go` and `done` instead!)
   - [x] We want information about parentage (if a FSM is managing a par arm, we want to know what the par itself is)?
- Loading in the trace
   - [x] Figure out what tool to use?
      - Kevin's [Wellen](https://github.com/ekiwi/wellen) library for Surfer
      - Some Python libraries for a first pass:
         - [pyDigitalWaveTools](https://pypi.org/project/pyDigitalWaveTools/)
         - [pyvcd](https://pyvcd.readthedocs.io/en/latest/)
         - [vcdvcd](https://pypi.org/project/vcdvcd/) :heavy_check_mark: 
   - [x] Make first pass script for reading vcd and outputting group lengths based on FSM values
   - [x] Remove assumption that there is only one FSM
   - [x] Remove assumption that each cycle takes 10ms (have a counter mechanism of how many cycles passed between X ms and Y ms)
      - [x] Sample signals on rising/falling clock edge ([comment](https://github.com/calyxir/calyx/issues/2014#issuecomment-2102867224))
   - [x] Check out example programs with parallelism
   - [x] Produce summary: compute the total cycles that a given group was active, the number of times it was active (the number of segments), and the average running time (which is just the quotient of the previous two values).
   - [x] Multi-component programs:
     - [x] Update TDCC to write one JSON file reflecting all components
     - [x] Output cell names info using a backend instead of TDCC?
     - [x] Fix hardcoding of `"TOP.TOP.main.go"`
   - [ ] Find edge cases where timing info is not actionable
   - [x] Don't start counting clock cycles until `main.go` is 1
- Make flame graphs
   - [ ] There is probably a library out there to generate a flame graph.
      - Flame graphs resource: https://www.brendangregg.com/flamegraphs.html
      - JavaScript library: https://github.com/spiermar/d3-flame-graph
      - https://profiler.firefox.com/
      - https://ui.perfetto.dev/
- [x] Write wrapper script around the pipeline

**Comment by rachitnigam** [comment]
Thanks for opening this @ayakayorihiro! Could you add the "Tracker" label to this issue?

**Comment by ayakayorihiro** [comment]
Thanks @rachitnigam ! Just added the tracker label, will keep in mind for next time :)

**Comment by ayakayorihiro** [comment]
Thanks @ekiwi ! I'll take a stab following your work with the `vcdvcd` library :)

**Comment by ayakayorihiro** [comment]
Closing this issue since I've been using a different tracking system for my TODOs.
