### ISSUE TITLE
Tracker: binary heaps

### ISSUE THREAD

**Issue by anshumanmohan** [calyxir/calyx#2067]
#1999 motivates the need for a general PIFO. It also discusses a made-up strategy for implementing such a PIFO. It leaves on the table, however, another straightforward solution: binary heaps.

This is a tracker for the things we need.
- [x] A module that accepts values and `push`es them into a min-heap ordered by value. *Done via #2074*
- [x] Tweak the above to accept a value and a rank, and `push` a (value, rank) [tuple](https://github.com/calyxir/calyx/blob/513fda8bff119eea97e645b19dbbacf674f8a5a0/calyx-py/test/correctness/tuple.py) ordered by rank. *Done via #2145*
- [x] Modify the above to obey the [queue interface](https://docs.calyxir.org/frontends/queues.html#shared-interface). It won't be possible to obey the interface exactly, since the binary heap will need ranks as well as values, but maybe get it close. *Done via #2145*
- [x] Add `peek` and `pop` functionality. *Done via #2145*
- [x] Test! *Done via #2174*
- [x] Document! *Done via #2182*
- [x] Write logic for a _scheduling transaction_ that interacts with the above, granting ranks to values. The scheduling transaction + binary heap combination will be able to obey the [queue interface](https://docs.calyxir.org/frontends/queues.html#shared-interface) exactly.
    - [x] A basic first goal for this would be a scheduling transaction that achieves fairness among the incoming classes of traffic; if we can do this then the scheduling transaction + binary heap would become a drop-in replacement for our super limited [PIFO](https://docs.calyxir.org/frontends/queues.html#pifo) that can only do fairness. 
    *Done via #2174*
    - [x] More generally, there is lots of room to run here. Other scheduling transactions can achieve other goals, and our super limited PIFO will not be able to match this behavior. Sorta the point of a truly general PIFO. See [this glossary](https://github.com/cucapra/packet-scheduling/discussions/13) for inspiration. It would be super if we had a little zoo of policies like this! 
    *Done via #2174*
- [x] #2187

**Comment by ethanuppal** [comment]
Does this issue have a PR or a branch?

**Comment by anshumanmohan** [comment]
PR for the first task coming soon. My intention is to leave the other tasks as little tasks for my BURE undergrads.

**Comment by anshumanmohan** [comment]
@ethanuppal see #2074 if you're curious!
