### ISSUE TITLE
[Cider Dap] Tracker

### ISSUE THREAD

**Issue by EclecticGriffin** [calyxir/calyx#2091]
A non-exhaustive list of things to be worked on with the Debug Adapter

- [ ] Missing installation and configuration instructions
- [ ] Figure out how to bundle the DAP binary (probably not easy or important)
- [ ] The multi-session mode crashes on opening half of the time
- [ ] The multi-session mode is not actually multi-session
