### ISSUE TITLE
Migrating tests to `fud2`

### ISSUE THREAD

**Issue by rachitnigam** [calyxir/calyx#2338]
Tracking the changes need to migrate the main test suite to a completely `fud2`-based test suite.
- [x] `calyx-py correctness` tests require piping into `fud2` which does not work.
- [x] https://github.com/calyxir/calyx/pull/2339
- [ ] Support for `vcd_json` stage
- [ ] Support for `ntt` stage
- [ ] Support for `systolic` stage
- [x] Support `dahlia` stage
- [x] https://github.com/calyxir/calyx/issues/2348 (Blocking usability issue)

**Comment by EclecticGriffin** [comment]
Superseded by #2479
